0: person
1: vehicle
2: girl
3: snail
4: skull
5: doughnut
6: oven
7: belt
8: zucchini
9: drink
10: ipod
11: canoe
12: goldfish
13: whisk
14: poster
15: stethoscope
16: spoon
17: chainsaw
18: zebra
19: brassiere
20: band-aid
